name: Deployer testing

on:
  pull_request:
    paths:
      - deployer/**
      - .github/workflows/pr-deployer.yml

# No GITHUB_TOKEN permissions, as we don't use it.
permissions: {}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false

      - name: Install Python
        id: setup-python
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
        with:
          python-version: "3.10"

      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: deployer/.venv
          key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}-${{ hashFiles('.github/workflows/pr-deployer.yml') }}-${{ steps.setup-python.outputs.python-version }}

      - name: Load cached .local
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: ~/.local
          key: dotlocal-${{ runner.os }}-${{ hashFiles('.github/workflows/pr-deployer.yml') }}-${{ steps.setup-python.outputs.python-version }}

      - name: Install Python poetry
        uses: snok/install-poetry@76e04a911780d5b312d89783f7b1cd627778900a # v1.4.1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Install deployer
        run: |
          cd deployer
          poetry install --with dev
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'

      - name: Lint Python code
        run: |
          source deployer/.venv/bin/activate
          flake8 deployer/src
          black --check deployer/src

      - name: Basic run of deployer
        run: |
          cd deployer
          poetry run deployer --help

      - name: Run deployer unit tests
        run: |
          cd deployer
          poetry run pytest
